"""Report Writer -- generates structured PDF reports from agent outputs."""

from __future__ import annotations

import logging
import os
import re
import uuid
from datetime import date

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.utils import simpleSplit
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.models.agent import AgentOutput

logger = logging.getLogger(__name__)

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports")

DEFAULT_SECTION_AGENT_MAP = {
    "Exec Summary": "action_recommender",
    "Macro": "macro_analyst",
    "Risk": "risk_assessor",
    "Recommendations": "action_recommender",
}

DISCLAIMER_TEXT = (
    "DISCLAIMER: This report is generated by an AI system for informational "
    "purposes only. It does not constitute financial advice. Always consult a "
    "qualified financial advisor before making investment decisions. Past "
    "performance is not indicative of future results."
)

PAGE_W, PAGE_H = A4
MARGIN_L = 0.75 * inch
MARGIN_R = 0.75 * inch
MARGIN_T = 0.75 * inch
MARGIN_B = 1.0 * inch

_NAVY = colors.HexColor("#1a365d")
_BLUE = colors.HexColor("#2b6cb0")
_GRAY_50 = colors.HexColor("#f7fafc")
_GRAY_200 = colors.HexColor("#e2e8f0")
_GRAY_500 = colors.HexColor("#718096")
_GRAY_700 = colors.HexColor("#4a5568")
_TBL_HDR = colors.HexColor("#2d3748")


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _md_inline(text: str) -> str:
    text = _esc(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<i>\1</i>", text)
    return text


def _draw_footer(canvas, doc):
    """Render disclaimer + page number in the footer of every page."""
    canvas.saveState()

    y_line = MARGIN_B - 0.15 * inch
    canvas.setStrokeColor(_GRAY_200)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN_L, y_line, PAGE_W - MARGIN_R, y_line)

    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(_GRAY_500)
    avail = PAGE_W - MARGIN_L - MARGIN_R
    lines = simpleSplit(DISCLAIMER_TEXT, "Helvetica", 6.5, avail)
    y_text = y_line - 10
    for ln in lines:
        canvas.drawString(MARGIN_L, y_text, ln)
        y_text -= 8

    canvas.setFont("Helvetica", 7)
    canvas.drawRightString(PAGE_W - MARGIN_R, 0.4 * inch, f"Page {doc.page}")

    canvas.restoreState()


def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "rpt_title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=28,
            textColor=_NAVY,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "rpt_subtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=12,
            leading=16,
            textColor=_GRAY_700,
            alignment=TA_CENTER,
            spaceAfter=2,
        ),
        "h1": ParagraphStyle(
            "rpt_h1",
            parent=base["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=22,
            textColor=_NAVY,
            spaceBefore=16,
            spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            "rpt_h2",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=_BLUE,
            spaceBefore=10,
            spaceAfter=4,
        ),
        "h3": ParagraphStyle(
            "rpt_h3",
            parent=base["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=_GRAY_700,
            spaceBefore=8,
            spaceAfter=3,
        ),
        "body": ParagraphStyle(
            "rpt_body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=colors.black,
            alignment=TA_JUSTIFY,
            spaceAfter=6,
        ),
        "bullet": ParagraphStyle(
            "rpt_bullet",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=colors.black,
            leftIndent=18,
            spaceAfter=3,
        ),
        "disclaimer_body": ParagraphStyle(
            "rpt_discl",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=11,
            textColor=_GRAY_500,
            spaceBefore=12,
        ),
        "tbl_hdr": ParagraphStyle(
            "rpt_tbl_hdr",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.white,
        ),
        "tbl_cell": ParagraphStyle(
            "rpt_tbl_cell",
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=colors.black,
        ),
    }


def _content_to_flowables(text: str, styles: dict[str, ParagraphStyle]) -> list:
    flowables: list = []
    current_para: list[str] = []

    def flush():
        if current_para:
            joined = " ".join(current_para)
            flowables.append(Paragraph(_md_inline(joined), styles["body"]))
            current_para.clear()

    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            flush()
            continue

        if stripped.startswith("### "):
            flush()
            flowables.append(Paragraph(_md_inline(stripped[4:]), styles["h3"]))
            continue
        if stripped.startswith("## "):
            flush()
            flowables.append(Paragraph(_md_inline(stripped[3:]), styles["h2"]))
            continue

        bullet_m = re.match(r"^[\*\-]\s+", stripped)
        if bullet_m:
            flush()
            item_text = stripped[bullet_m.end() :]
            flowables.append(Paragraph(f"\u2022\u2003{_md_inline(item_text)}", styles["bullet"]))
            continue

        current_para.append(stripped)

    flush()
    return flowables


class ReportWriter:
    @staticmethod
    def build_pdf(
        portfolio_name: str,
        agent_outputs: list[AgentOutput],
        sections: list[str],
        report_type: str,
        run_date: date,
        section_agent_map: dict[str, str] | None = None,
    ) -> str:
        import time as _time

        t0 = _time.perf_counter()
        logger.info(
            "ReportWriter.build_pdf starting: portfolio=%s type=%s sections=%d agent_outputs=%d",
            portfolio_name,
            report_type,
            len(sections),
            len(agent_outputs),
        )
        os.makedirs(REPORTS_DIR, exist_ok=True)
        styles = _build_styles()

        filename = f"report_{run_date.isoformat()}_{uuid.uuid4().hex[:8]}.pdf"
        filepath = os.path.join(REPORTS_DIR, filename)

        frame = Frame(
            MARGIN_L,
            MARGIN_B,
            PAGE_W - MARGIN_L - MARGIN_R,
            PAGE_H - MARGIN_T - MARGIN_B,
            id="main",
        )
        template = PageTemplate(id="report", frames=[frame], onPage=_draw_footer)
        doc = BaseDocTemplate(
            filepath,
            pagesize=A4,
            pageTemplates=[template],
            title=f"PortfolioIQ \u2013 {report_type.title()} Report",
            author="PortfolioIQ AI System",
        )

        story: list = []

        story.append(Spacer(1, 1.5 * inch))
        story.append(Paragraph("PortfolioIQ Report", styles["title"]))
        story.append(Spacer(1, 8))
        type_label = report_type.replace("_", " ").title()
        story.append(
            Paragraph(
                f"{type_label} Report &mdash; {_esc(portfolio_name)}",
                styles["subtitle"],
            )
        )
        story.append(Paragraph(f"Generated: {run_date.isoformat()}", styles["subtitle"]))
        story.append(PageBreak())

        effective_map = {**DEFAULT_SECTION_AGENT_MAP, **(section_agent_map or {})}

        output_map: dict[str, AgentOutput] = {}
        for o in agent_outputs:
            output_map[o.agent_name] = o

        for section_name in sections:
            agent_name = effective_map.get(section_name)
            if not agent_name:
                continue
            output = output_map.get(agent_name)
            if not output:
                continue

            display = "Executive Summary" if section_name == "Exec Summary" else section_name
            story.append(Paragraph(display, styles["h1"]))

            summary = output.summary or ""
            if section_name == "Recommendations" and "Exec Summary" in sections:
                exec_end = summary.find("\n\n", 500)
                text = summary[exec_end:].strip()[:3000] if exec_end > 0 else summary[:3000]
            elif section_name == "Exec Summary":
                exec_end = summary.find("\n\n", 200)
                text = summary[:exec_end].strip() if exec_end > 0 else summary[:800]
            else:
                text = summary[:3000]

            story.extend(_content_to_flowables(text, styles))

            if output.predictions:
                preds = output.predictions if isinstance(output.predictions, list) else []
                if preds:
                    story.append(Spacer(1, 8))
                    story.append(Paragraph("Predictions", styles["h2"]))
                    story.append(Spacer(1, 4))

                    header = [
                        Paragraph("Prediction", styles["tbl_hdr"]),
                        Paragraph("Confidence", styles["tbl_hdr"]),
                        Paragraph("Timeframe", styles["tbl_hdr"]),
                    ]
                    data = [header]
                    for pred in preds[:5]:
                        data.append(
                            [
                                Paragraph(
                                    _esc(str(pred.get("prediction", ""))[:200]),
                                    styles["tbl_cell"],
                                ),
                                Paragraph(
                                    _esc(str(pred.get("confidence", ""))),
                                    styles["tbl_cell"],
                                ),
                                Paragraph(
                                    _esc(str(pred.get("timeframe", ""))),
                                    styles["tbl_cell"],
                                ),
                            ]
                        )

                    avail_w = PAGE_W - MARGIN_L - MARGIN_R
                    tbl = Table(
                        data,
                        colWidths=[avail_w * 0.62, avail_w * 0.16, avail_w * 0.22],
                        repeatRows=1,
                    )
                    tbl.setStyle(
                        TableStyle(
                            [
                                ("BACKGROUND", (0, 0), (-1, 0), _TBL_HDR),
                                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                                ("GRID", (0, 0), (-1, -1), 0.5, _GRAY_200),
                                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _GRAY_50]),
                                ("TOPPADDING", (0, 0), (-1, -1), 5),
                                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                            ]
                        )
                    )
                    story.append(tbl)

            if output.judge_overall_score is not None:
                story.append(Spacer(1, 6))
                score = float(output.judge_overall_score)
                story.append(
                    Paragraph(
                        f"<b>Judge Accuracy Score:</b> {score:.1f}/10",
                        styles["body"],
                    )
                )

            story.append(Spacer(1, 12))

        story.append(Spacer(1, 16))
        story.append(Paragraph("Disclaimers", styles["h1"]))
        story.append(Paragraph(_esc(DISCLAIMER_TEXT), styles["disclaimer_body"]))

        doc.build(story)
        elapsed_ms = int((_time.perf_counter() - t0) * 1000)
        logger.info("ReportWriter.build_pdf complete: %s (elapsed=%dms)", filepath, elapsed_ms)
        return filepath
