"""Report Writer -- generates structured .docx reports from agent outputs."""

from __future__ import annotations

import logging
import os
import uuid
from datetime import date

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.models.agent import AgentOutput

logger = logging.getLogger(__name__)

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports")

SECTION_AGENT_MAP = {
    "Exec Summary": "action_recommender",
    "AI Stack": "ai_stack_analyst",
    "Gold": "gold_analyst",
    "Defence": "defence_analyst",
    "Macro": "macro_analyst",
    "Risk": "risk_assessor",
    "Recommendations": "action_recommender",
}

DISCLAIMER_TEXT = (
    "DISCLAIMER: This report is generated by an AI system for informational purposes only. "
    "It does not constitute financial advice. Always consult a qualified financial advisor "
    "before making investment decisions. Past performance is not indicative of future results."
)


class ReportWriter:
    @staticmethod
    def build_docx(
        portfolio_name: str,
        agent_outputs: list[AgentOutput],
        sections: list[str],
        report_type: str,
        run_date: date,
    ) -> str:
        os.makedirs(REPORTS_DIR, exist_ok=True)

        doc = Document()

        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(11)

        title = doc.add_heading(f"PortfolioIQ Report", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(
            f"{report_type.replace('_', ' ').title()} Report -- {portfolio_name}\n"
            f"Generated: {run_date.isoformat()}"
        )
        run.font.size = Pt(12)
        run.font.color.rgb = None

        doc.add_page_break()

        output_map: dict[str, AgentOutput] = {}
        for o in agent_outputs:
            output_map[o.agent_name] = o

        for section_name in sections:
            agent_name = SECTION_AGENT_MAP.get(section_name)
            if not agent_name:
                continue

            output = output_map.get(agent_name)
            if not output:
                continue

            if section_name == "Recommendations" and "Exec Summary" in sections:
                doc.add_heading("Recommendations", level=1)
                summary = output.summary
                exec_end = summary.find("\n\n", 500)
                if exec_end > 0:
                    doc.add_paragraph(summary[exec_end:].strip()[:3000])
                else:
                    doc.add_paragraph(summary[:3000])
            elif section_name == "Exec Summary":
                doc.add_heading("Executive Summary", level=1)
                summary = output.summary
                exec_end = summary.find("\n\n", 200)
                if exec_end > 0:
                    doc.add_paragraph(summary[:exec_end].strip())
                else:
                    doc.add_paragraph(summary[:800])
            else:
                doc.add_heading(section_name, level=1)
                doc.add_paragraph(output.summary[:3000])

            if output.predictions:
                doc.add_heading("Predictions", level=2)
                table = doc.add_table(rows=1, cols=3)
                table.style = "Light Grid Accent 1"
                hdr = table.rows[0].cells
                hdr[0].text = "Prediction"
                hdr[1].text = "Confidence"
                hdr[2].text = "Timeframe"

                preds = output.predictions if isinstance(output.predictions, list) else []
                for pred in preds[:5]:
                    row = table.add_row().cells
                    row[0].text = str(pred.get("prediction", ""))[:200]
                    row[1].text = str(pred.get("confidence", ""))
                    row[2].text = str(pred.get("timeframe", ""))

            if output.judge_overall_score is not None:
                doc.add_paragraph(
                    f"Judge Accuracy Score: {float(output.judge_overall_score):.1f}/10"
                )

            doc.add_paragraph("")

        doc.add_heading("Disclaimers", level=1)
        doc.add_paragraph(DISCLAIMER_TEXT)

        filename = f"report_{run_date.isoformat()}_{uuid.uuid4().hex[:8]}.docx"
        filepath = os.path.join(REPORTS_DIR, filename)
        doc.save(filepath)

        logger.info("Report written: %s", filepath)
        return filepath
