import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto max-w-3xl px-4 py-12">
        <Link to="/">
          <Button variant="ghost" size="sm" className="mb-6">
            <ArrowLeft className="h-4 w-4 mr-1" /> Back
          </Button>
        </Link>

        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

        <div className="prose prose-invert max-w-none space-y-6 text-sm text-muted-foreground">
          <p><strong>Effective Date:</strong> March 2026</p>

          <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p>
            By accessing or using PortfolioIQ ("the Service"), you agree to be bound by these Terms of Service.
            If you do not agree, you may not use the Service.
          </p>

          <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
          <p>
            PortfolioIQ is an AI-powered portfolio analysis tool that provides informational insights
            about ETF portfolios. The Service uses artificial intelligence agents to generate analysis,
            predictions, and recommendations based on publicly available market data.
          </p>

          <h2 className="text-lg font-semibold text-foreground">3. Not Financial Advice</h2>
          <p>
            <strong>The Service does not provide financial advice.</strong> All analyses, predictions,
            recommendations, and reports generated by PortfolioIQ are for informational and educational
            purposes only. They should not be relied upon as the sole basis for any investment decision.
            Always consult a qualified financial advisor before making investment decisions.
          </p>

          <h2 className="text-lg font-semibold text-foreground">4. AI-Generated Content</h2>
          <p>
            Content generated by PortfolioIQ's AI agents may contain inaccuracies, errors, or outdated
            information. The accuracy scores and confidence indicators reflect the system's self-assessment
            and should not be interpreted as guarantees of accuracy.
          </p>

          <h2 className="text-lg font-semibold text-foreground">5. User Responsibilities</h2>
          <p>
            You are responsible for: maintaining the confidentiality of your account credentials;
            all activity that occurs under your account; verifying any information before acting on it;
            and complying with all applicable laws and regulations.
          </p>

          <h2 className="text-lg font-semibold text-foreground">6. Data and Privacy</h2>
          <p>
            Your use of the Service is also governed by our <Link to="/privacy" className="underline text-primary">Privacy Policy</Link>.
            Portfolio data you provide is stored securely and used solely to deliver the Service.
          </p>

          <h2 className="text-lg font-semibold text-foreground">7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, PortfolioIQ and its operators shall not be liable
            for any indirect, incidental, special, consequential, or punitive damages, or any loss of
            profits or revenues, whether incurred directly or indirectly, or any loss of data, arising
            from your use of the Service.
          </p>

          <h2 className="text-lg font-semibold text-foreground">8. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the Service after
            changes constitutes acceptance of the updated terms.
          </p>
        </div>
      </div>
    </div>
  );
}
